site_name: Pokétop RPG
docs_dir: source
site_dir: docs
site_url: https://TEParsons.github.io/Poketop-RPG

theme:
  name: mkdocs
  user_color_mode_toggle: true
  navigation_depth: 5

nav:
  - ...

hooks:
  - utils/ipa.py
  - utils/links.py

extra_css:
  - extra_style.css

validation:
  absolute_links: ignore

markdown_extensions:
  - nl2br
  - extra
  - wikilinks

plugins:
  - awesome-pages
